baseURL = "https://acarril.github.io"
title = "Álvaro Carril"
theme = "etch-academic"
languageCode = "en-US"
enableInlineShortcodes = true
enableGitInfo = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
    description = "every one and every zero"
    copyright = "Álvaro Carril — Content licensed under GNU GPL-3.0-only"
    dark = "off"
    highlight = true
    aboutExcerptSentences = 5
    google_analytics = "G-3F4R1K00EF"

[menu]
    [[menu.main]]
        identifier = "cv"
        name = "cv"
        title = "cv"
        url = "https://www.dropbox.com/s/oow36pf0wyevnc4/CV_acarril.pdf?raw=1"
        weight = 40

    [[menu.main]]
        identifier = "about"
        name = "about"
        title = "about"
        url = "/about/"
        weight = 30

    [[menu.main]]
        identifier = "resources"
        name = "resources"
        title = "Resources"
        url = "/resources"
        weight = 20

    [[menu.main]]
        identifier = "research"
        name = "research"
        title = "research"
        url = "/research/"
        weight = 10

[permalinks]
    posts = "/:title/"

[markup.goldmark.renderer]
    # Allows HTML in Markdown
    unsafe = true