baseURL = "https://acarril.github.io"
title = "Álvaro Carril"
theme = "etch-academic"
languageCode = "en-US"
enableInlineShortcodes = true
enableGitInfo = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
    description = "every one and every zero"
    copyright = "Álvaro Carril — Content licensed under GNU GPL-3.0-only"
    dark = "off"
    highlight = true
    aboutExcerptSentences = 5
    google_analytics = "G-3F4R1K00EF"
    profile_image = "img/09_headshot.jpg"
    github = "https://github.com/acarril"
    linkedin = "https://www.linkedin.com/in/alvaro-carril/"

    [[params.social]]
    icon_name = "github"
    url = "https://github.com/acarril"

    [[params.social]]
    icon_name = "linkedin"
    url = "https://www.linkedin.com/in/alvaro-carril/"

[menu]
    [[menu.main]]
        identifier = "resume"
        name = "Resume"
        title = "resume"
        url = "/resume"
        weight = 40

    [[menu.main]]
        identifier = "about"
        name = "About"
        title = "about"
        url = "/about/"
        weight = 30

#    [[menu.main]]
#        identifier = "resources"
#        name = "Resources"
#        title = "Resources"
#        url = "/resources"
#        weight = 20

    [[menu.main]]
        identifier = "research"
        name = "Research"
        title = "research"
        url = "/research/"
        weight = 10

[permalinks]
    posts = "/:title/"

[markup.goldmark.renderer]
    # Allows HTML in Markdown
    unsafe = true

[module]
[[module.imports]]
    path = 'github.com/hugomods/icons/vendors/bootstrap'