# Workflow for building and deploying a Hugo site to GitHub Pages
name: Hugo deployment

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash for run steps
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.120.4 # Pin your Hugo version for reproducible builds
      # NODE_VERSION: '18' # Optional: Define if you need a specific Node.js version globally

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # Fetches all history for .GitInfo, .Lastmod, etc.
          submodules: recursive   # Checkout submodules (e.g., themes)

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true # Installs the extended version of Hugo (includes Dart Sass)

      # Conditionally setup Node.js and install dependencies if a lock file is present
      - name: Setup Node.js
        if: hashFiles('package-lock.json', 'npm-shrinkwrap.json') != ''
        uses: actions/setup-node@v4
        with:
          # node-version: ${{ env.NODE_VERSION }} # Or specify version directly, e.g., '18.x'
          node-version-file: '.nvmrc' # Recommended: use a .nvmrc file to specify Node version
          cache: 'npm' # Caches npm dependencies for faster builds

      - name: Install Node.js dependencies
        if: hashFiles('package-lock.json', 'npm-shrinkwrap.json') != ''
        run: npm ci # Use 'ci' for cleaner, faster, and more reliable installs in CI

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production # Standard variable for Hugo production builds
        run: |
          hugo \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3 # Specifically for GitHub Pages
        with:
          path: ./public # Path to the public directory Hugo builds to

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # Ensures the build job completes before deploying
    # Permissions are inherited from the workflow level
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
